### ISSUE TITLE
assertNotNull is not reliable with inputs containing single quotes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shunit2#14]
```
What steps will reproduce the problem?
1. assertNotNull 'error-msg-4' "xxx there's no /x/y"

What is the expected output? What do you see instead?
The assertion above fails despite it should not.

What version of the product are you using? On what operating system?
# tested shunit2 versions: shUnit 2.1.5 and shUnit 2.0.3
# shell: GNU bash, version 3.2.48(21)-release (i686-pc-cygwin)
# uname -s: CYGWIN_NT-5.1
# uname -r: 1.5.25(0.156/4/2)
# uname -v: 2008-06-12 19:34
# uname -m: i686
# uname -p: unknown
# uname -i: unknown
# uname -o: Cygwin


Please provide any additional information below.
See attached file (test_assertNotNull.zip) that contains a test script and
the produced output for each of the tested version of shUnit.

```

Original issue reported on code.google.com by `GVa...@gmail.com` on 18 May 2009 at 1:45

Attachments:
- [test_assertNotNull.zip](https://storage.googleapis.com/google-code-attachments/shunit2/issue-14/comment-0/test_assertNotNull.zip)

**Comment by eyherabh** [comment]
The version of _shunit_escapeCharactersInString in master is not quoting single quotes properly. The string **Hello'world** is turned into **Hello'world\'**. It is possibly to fix it but not using sed but just plain shell builtins common to all supported shells. However, that is unnecessary.
Turns out this functions is only used in assertNotNull and assertNull. For those cases, only leaving the string non-empty when those characters are present is sufficient. Hence, I would rather do that and remove the quoting functions. More performant and less maintenance.
