### ISSUE TITLE
sourcing multiple test scripts

### ISSUE THREAD

**Issue by pomke** [kward/shunit2#97]
Hello ^_^

I have a simple function that I was using in my test-runner script:
```sh
# loads all scripts passed in, ie:  RunTests ./test_*   would get all test_* files
# once loaded it then sources shunit2 which runs all test functions
RunTests() {
	# Load all files passed in as $@
	for f in $@
	do
		echo "loading test script $f"
		. $f
	done

	# run shunit
	. $DIR/shunit2
}
```

This worked well right up until I added a 2nd test file. All of my test files get sourced but shunit2 seems to then import the first test file a 2nd time, then ignores all other tests.  a call to `declare -F` just before sourcing shunit2 shows that all of my test functions from all sourced test scripts are defined as expected.

**Comment by kward** [comment]
The recommended method is to define your own suite using a `suite()` function. See `examples/suite_test.sh` for a simple example.

In the code you've provided, the issue is that shunit2 looks at the `$#` variable to determine whether it was run sourced or standalone. In this case, the $# variable will hold the number of files passed into the `RunTests()` function. A simple fix would be to use `shift` to remove the filename arguments after they've been read. The following code works.

```shell
RunTests() {
  # Load all files passed in as $@.
  for f in $@; do
    shift  # <-- THIS LINE WAS ADDED.
    echo "loading test script $f"
    . $f
  done

  # Run shunit2.
  . ${DIR}/shunit2
}
```
